### ISSUE TITLE
Add license to repo + website

### ISSUE THREAD

**Issue by jangondol** [pyconsk/2016.pycon.sk#15]
The repository currently doesn't have a LICENSE file. Also, there's no visible mention of copyright on the website.

Suggestion: [MIT license](http://choosealicense.com/licenses/mit/) for code (GitHub repo), [CC-BY](https://creativecommons.org/licenses/by/4.0/) for content (mentioned in page footers). Let's make clear that only content we have created ourselves is licensed CC-BY (and not logos etc.).

**Comment by ricco386** [comment]
Sure, feel free to update website.

**Comment by dn0** [comment]
:+1:

**Comment by ricco386** [comment]
Lincese updated.
