### ISSUE TITLE
PyVideo data

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2016.pycon.sk#19]
Once all talks are published, we shall create a MR to: https://github.com/pyvideo/pyvideo-data/

**Comment by dn0** [comment]
pyvideo is dead - have a look at http://www.pyvideo.org/

**Comment by ricco386** [comment]
I know I have seen that the page is dead, but there is project on github where there is still possibility to send PR and that is meant to carry on...

**Comment by ricco386** [comment]
We have never added the MR, closing this issue
